name: stips

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - python>=3.7

  - matplotlib>=3.1.1
  - astropy

  - photutils
  - healpy
  - pysynphot
  - esutil

  # Docs
  - sphinx
  - docutils
  - stsci_rtd_theme

  - pip:

    - webbpsf
    - pandeia.engine==1.5
    - jwst_backgrounds


    # Docs
    - sphinx_astropy
    - automodinit


