name: stips

channels:
    - astropy

dependencies:
    - python>=3.7
    - astropy
    - Cython
    - matplotlib
    - numpy >= 1.13
    - sphinx-astropy
    - astropy-helpers

   - pip:
       - stsci_rtd_theme
