name: stips

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  - python>=3.7
  - astropy
  - Cython
  - matplotlib
  - numpy >= 1.13
  - sphinx-astropy

  - pip:
    - stsci_rtd_theme
