# This file describes a conda environment that can be to install STIPS
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ source activate stips
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n stips

name: stips

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults

dependencies:
  # Base dependencies
  - python>=3.7
  - pip
  - jupyter
  - Cython

  - pip:
    # Major modules
    - ConfigParser
    - numpy
    - scipy
    - matplotlib
    - astropy
    - photutils
    - healpy
    - synphot
    - stsynphot
    - esutil --no-binary=esutil
    - jwst_backgrounds
    - webbpsf>=0.9.0
    - pandeia.engine==1.6

    # Minor modules
    - montage-wrapper
    - pyyaml
    - mechanize

    # Docs
    - sphinx
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - sphinx_automodapi
    - sphinx_autoapi
    
    # Testing
    - tox
    - tox-conda
    - pytest-astropy
    
    # Current package
    - -e .
