# This file describes a conda environment that can be to install STIPS
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ source activate stips
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n stips

name: stips

channels:
  - conda-forge
  - astropy
  - defaults

dependencies:
  # Base dependencies
  - pip
  - python>=3.8
  - jupyter
  - Cython
  - esutil

  - pip:
    # Core Modules
    - webbpsf==1.0.0
    - poppy==1.0.3
    - pandeia.engine==1.7
    - synphot==1.1.1
    - stsynphot==1.1.0
  
    # Major modules
    - astropy
    - photutils
    - ConfigParser
    - numpy==1.22.3
    - scipy
    - matplotlib
    - ipython==7.31.1

    # Minor modules
    - montage-wrapper
    - pyyaml
    - mechanize

    # Docs
    - docutils
    - sphinx
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - sphinx_automodapi
    - sphinx_autoapi
    - astropy_helpers

    # Testing
    - tox
    - tox-conda
    - pytest-astropy
    
    # Current package
    - -e .
