# This file describes a conda environment that can be to install STIPS
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ source activate stips
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n stips

name: stips

channels:
  - conda-forge
  - astropy
  - http://ssb.stsci.edu/astroconda

dependencies:
  # Base dependencies
  - pip
  - python>=3.7
#  - Cython
  - jupyter

  # Minor modules
  - pyfftw
  - ConfigParser

  # Docs
  - sphinx
  - docutils
  - sphinx_rtd_theme
  - stsci_rtd_theme

  # Testing
  - pytest-astropy

  - pip:
    # Major modules
    - numpy
    - scipy
    - matplotlib
    - astropy
    - photutils
    - healpy
    - synphot
    - stsynphot
    - esutil
    - jwst_backgrounds
    - webbpsf>=0.9.0
    - pandeia.engine==1.5.2

    # Minor modules
    - montage-wrapper
    - pyyaml
    - mechanize

    # Docs
    - astropy_helpers
    - sphinx_astropy
