# GitHub Actions workflow for testing and continuous integration.

name: CI

on:
  push:
  pull_request:

jobs:
  ci_tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:

          - name: Python 2.7
            os: ubuntu-latest
            python: 2.7

          - name: Python 3.7
            os: ubuntu-latest
            python: 3.7

          - name: Python 3.8
            os: ubuntu-latest
            python: 3.8

          - name: Python 3.8 Mac
            os: macos-latest
            python: 3.8

          - name: Python 3.8 Long
            os: ubuntu-latest
            python: 3.8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: stips
        environment-file: environment.yml
        python-version: ${{ matrix.python }}
        auto-activate-base: false
    - name: Install Required Data
      shell: bash -l {0}
      run: |
        export TEST_DATA=${HOME}/test_data
        mkdir -p ${TEST_DATA}
        wget https://stsci.box.com/shared/static/4nebx2ndxr7c77lgocfbvxo7c2hyd3in.tgz -O ${TEST_DATA}/stips_data_current.tar.gz
        tar -xzvf ${TEST_DATA}/stips_data_current.tar.gz -C ${TEST_DATA}
        mkdir -p ${TEST_DATA}/synphot
        wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot1.tar.gz -O ${TEST_DATA}/synphot1.tar.gz
        tar -xzvf ${TEST_DATA}/synphot1.tar.gz -C ${TEST_DATA}/synphot/
        wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot2.tar.gz -O ${TEST_DATA}/synphot2.tar.gz
        tar -xzvf ${TEST_DATA}/synphot2.tar.gz -C ${TEST_DATA}/synphot/
        wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot5.tar.gz -O ${TEST_DATA}/synphot5.tar.gz
        tar -xzvf ${TEST_DATA}/synphot5.tar.gz -C ${TEST_DATA}/synphot/
        wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot6.tar.gz -O ${TEST_DATA}/synphot6.tar.gz
        tar -xzvf ${TEST_DATA}/synphot6.tar.gz -C ${TEST_DATA}/synphot/
        wget -qO- https://stsci.box.com/shared/static/7voehzi5krrpml5wgyg8bo954ew7arh2.gz -O ${TEST_DATA}/pandeia_data-1.5.2rc2_roman.gz
        tar -xzvf ${TEST_DATA}/pandeia_data-1.5.2rc2_roman.gz -C ${TEST_DATA}
        wget -qO- https://stsci.box.com/shared/static/qcptcokkbx7fgi3c00w2732yezkxzb99.gz -O ${TEST_DATA}/webbpsf_data.gz
        tar -xzvf ${TEST_DATA}/webbpsf_data.gz -C ${TEST_DATA}
    - name: Test with pytest
      shell: bash -l {0}
      if ${{ matrix.name != 'Python 3.8 Long' }}
      run: |
        export stips_data=${HOME}/test_data/stips_data
        export PYSYN_CDBS=${HOME}/test_data/synphot/grp/hst/cdbs
        export pandeia_refdata=${HOME}/test_data/pandeia_data-1.5.2rc2_roman
        export WEBBPSF_PATH=${HOME}/test_data/webbpsf-data
        pytest -m "not veryslow" stips
    - name: Test slow tests with pytest
      shell: bash -l {0}
      if ${{ matrix.name == 'Python 3.8 Long' }}
      run: |
        export stips_data=${HOME}/test_data/stips_data
        export PYSYN_CDBS=${HOME}/test_data/synphot/grp/hst/cdbs
        export pandeia_refdata=${HOME}/test_data/pandeia_data-1.5.2rc2_roman
        export WEBBPSF_PATH=${HOME}/test_data/webbpsf-data
        pytest stips

  docs_test:
    name: "docs_test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: stips
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false
    - name: Build Docs
      shell: bash -l {0}
      run: |
        python setup.py build_docs -w
